doctrine:
    dbal:
        #url: '%env(resolve:DATABASE_URL)%'
        #url: postgresql://aspirador:'%env(resolve:DATABASE_PASSWORD)%'@aspirador-db:5432/aspirador?serverVersion=13&charset=utf8

        dbname:               aspirador
        host:                 aspirador-db
        port:                 5432
        user:                 aspirador
        password:             '%env(resolve:DATABASE_PASSWORD)%'
        driver:               pdo_pgsql
        charset:              utf8
        server_version: '13'

        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
