version: '3.9'

services:
  db:
    container_name: aspirador-db
    image: "postgres:13"
    restart: on-failure
    volumes:
      - "./docker/database/pgdata:/var/lib/postgresql/data/pgdata:rw"
    environment:
      - POSTGRES_USER=aspirador
      - POSTGRES_DB=aspirador
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=4Sp1r4d0r
    ports:
      - 5432:5432

  php:
    container_name: aspirador-bot
    image: cedroigor/aspirador-bot
    build:
      context: .
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - PHP_DATE_TIMEZONE="America/Sao_Paulo"
    command: bash
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

networks:
  default:
    name: econciliador
    external: true
